name: hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu_latest
    steps:
      - name: hello world      
        uses: actions/checkout@v2
        run: echo "Hello world"
        shell: bash
  goodbye:
    runs-on: ubuntu_latest
    steps:
      - name: goodbye world
        run: echo "Goodbye world"
        shell: bash